### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by istvanvasil** [danvk/expandable-image-grid#7]
Hi there! What a great work. This kind of functionality is exactly what I am looking for. I am however new to developing and would need some help. This might be time consuming to figure it out but if it's an easy answer I would really appreciate your feedback. 

How would this plugin work if I would like to have my gallery loaded through <?php foreach... ?> and whatever content I want in the expanded view through another <?php foreach...?>

Thanks!

**Comment by danvk** [comment]
I'm glad you're interested in expandable-image-grid, but this isn't a good venue for basic PHP questions. I'm sure there are some mailing lists or chat forums where you can find help.
